### ISSUE TITLE
Unable to build VRS on my Mac

### ISSUE THREAD

**Issue by lmathia2** [facebookresearch/vrs#50]
## Instructions To Reproduce the 🐛 Bug:

1. Full runnable code or full changes you made:
None

2. What exact command you run:
```
brew install cmake ninja ccache boost fmt cereal libpng jpeg lz4 zstd xxhash googletest
brew install node doxygen
cmake -S vrs -B vrs_build  '-GCodeBlocks - Ninja'
cd vrs_build
ninja all
```

3. **Full logs** or other relevant observations:

```
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_CXX_COMPILER: /Library/Developer/CommandLineTools/usr/bin/c++
-- CMAKE_CXX_COMPILER_VERSION: 13.1.6.13160021
-- CCACHE enabled
-- Found Boost: /Users/mathiasl/.brew/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: filesystem chrono date_time system thread
-- Found Fmt: /Users/mathiasl/.brew/lib/libfmt.dylib
-- Found Cereal: /Users/mathiasl/.brew/include
-- Found Lz4: /Users/mathiasl/.brew/lib/liblz4.dylib
-- Found Zstd: /Users/mathiasl/.brew/lib/libzstd.dylib
-- Found xxHash: /Users/mathiasl/.brew/lib/libxxhash.dylib
-- Found Png: /Users/mathiasl/.brew/lib/libpng.dylib
-- Found Jpeg: /Users/mathiasl/.brew/lib/libjpeg.dylib
-- Found GTest: /Users/mathiasl/.brew/anaconda3/lib/cmake/GTest/GTestConfig.cmake (found version "1.10.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mathiasl/Projects/cvpr_release_data/src/vrs_build
(base) mathiasl-mbp:src mathiasl$ cd vrs_build/
(base) mathiasl-mbp:vrs_build mathiasl$ ninja all
[48/132] Linking CXX executable vrs/helpers/test_vrs_helpers
FAILED: vrs/helpers/test_vrs_helpers vrs/helpers/test_vrs_helpers[1]_tests.cmake /Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/helpers/test_vrs_helpers[1]_tests.cmake
: && /Users/mathiasl/.brew/bin/ccache /Library/Developer/CommandLineTools/usr/bin/c++ -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  vrs/helpers/CMakeFiles/test_vrs_helpers.dir/test/StringsTest.cpp.o -o vrs/helpers/test_vrs_helpers  vrs/helpers/libvrs_helpers.a  vrs/os/libvrs_os.a  vrs/oss/logging/libvrs_logging.a  /Users/mathiasl/.brew/lib/libfmt.dylib  /Users/mathiasl/.brew/lib/libboost_system-mt.dylib  /Users/mathiasl/.brew/lib/libboost_filesystem-mt.dylib  /Users/mathiasl/.brew/lib/libboost_atomic-mt.dylib  /Users/mathiasl/.brew/lib/libboost_thread-mt.dylib  /Users/mathiasl/.brew/lib/libboost_chrono-mt.dylib  /Users/mathiasl/.brew/lib/libboost_date_time-mt.dylib  /Users/mathiasl/.brew/anaconda3/lib/libgtest_main.1.10.0.dylib  /Users/mathiasl/.brew/anaconda3/lib/libgtest.1.10.0.dylib && cd /Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/helpers && /Users/mathiasl/.brew/Cellar/cmake/3.23.1_1/bin/cmake -D TEST_TARGET=test_vrs_helpers -D TEST_EXECUTABLE=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/helpers/test_vrs_helpers -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/helpers -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_FILTER= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=test_vrs_helpers_TESTS -D CTEST_FILE=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/helpers/test_vrs_helpers[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=5 -D TEST_XML_OUTPUT_DIR= -P /Users/mathiasl/.brew/Cellar/cmake/3.23.1_1/share/cmake/Modules/GoogleTestAddTests.cmake
Undefined symbols for architecture x86_64:
  "typeinfo for testing::Test", referenced from:
      typeinfo for StringsHelpersTester in StringsTest.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[55/132] Building CXX object vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o
FAILED: vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o
/Users/mathiasl/.brew/bin/ccache /Library/Developer/CommandLineTools/usr/bin/c++ -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DOSS_BUILD_MODE -I/Users/mathiasl/Projects/cvpr_release_data/src/vrs -I/Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/oss -isystem /Users/mathiasl/.brew/anaconda3/include -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -std=c++17 -MD -MT vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o -MF vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o.d -o vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o -c /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/test/FilteredFileReaderTest.cpp
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/test/FilteredFileReaderTest.cpp:25:
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/FilteredFileReader.h:27:
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/RecordFileReader.h:33:
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/RecordReaders.h:21:
/Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/ErrorCode.h:22:10: fatal error: 'fmt/format.h' file not found
#include <fmt/format.h>
         ^~~~~~~~~~~~~~
1 error generated.
[58/132] Building CXX object vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o
FAILED: vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o
/Users/mathiasl/.brew/bin/ccache /Library/Developer/CommandLineTools/usr/bin/c++ -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DOSS_BUILD_MODE -I/Users/mathiasl/Projects/cvpr_release_data/src/vrs -I/Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/oss -isystem /Users/mathiasl/.brew/anaconda3/include -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -std=c++17 -MD -MT vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o -MF vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o.d -o vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o -c /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/test/PixelFrameTest.cpp
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/test/PixelFrameTest.cpp:24:
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/RecordFileReader.h:33:
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/RecordReaders.h:21:
/Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/ErrorCode.h:22:10: fatal error: 'fmt/format.h' file not found
#include <fmt/format.h>
         ^~~~~~~~~~~~~~
1 error generated.
[65/132] Building CXX object vrs/CMakeFiles/vrslib.dir/DataLayout.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by georges-berenger** [comment]
thanks for reporting. We're seeing the issue and will fix it asap.

**Comment by georges-berenger** [comment]
1.

**Comment by SeaOtocinclus** [comment]
Should now be fixed by #51 that has been merged later today

**Comment by lmathia2** [comment]
I did a git pull, and retried the steps above, but still get exactly the same error. Not sure what is broken in my brew setup.

**Comment by georges-berenger** [comment]
I'm confused, because we're getting different versions of libraries (I don't think we need to worry about xcode):
```
~/Cache$ rm -rf vrs_build/
~/Cache$ cmake -S oss-vrs -B vrs_build  '-GCodeBlocks - Ninja'
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode_13.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_CXX_COMPILER: /Applications/Xcode_13.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- CMAKE_CXX_COMPILER_VERSION: 13.0.0.13000029
-- CCACHE enabled
-- Found Boost: /usr/local/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: filesystem chrono date_time system thread
-- Found Lz4: /usr/local/lib/liblz4.dylib
-- Found Zstd: /usr/local/lib/libzstd.dylib
-- Found xxHash: /usr/local/lib/libxxhash.dylib
-- Found ZLIB: /Applications/Xcode_13.2.1_fb.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/libz.tbd (found version "1.2.11")
-- Found PNG: /usr/local/lib/libpng.dylib (found version "1.6.37")
-- Found JPEG: /usr/local/lib/libjpeg.dylib (found version "90")
-- Found GTest: /usr/local/lib/cmake/GTest/GTestConfig.cmake (found version "1.11.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/gberenger/Cache/vrs_build
~/Cache$ cd vrs_build/
~/Cache/vrs_build$ ninja
[115/132] Linking CXX static library sample_code/libsample_code_app.a
/Applications/Xcode_13.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: sample_code/libsample_code_app.a(SampleImageReader.cpp.o) has no symbols
/Applications/Xcode_13.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: sample_code/libsample_code_app.a(SampleRecordAndPlay.cpp.o) has no symbols
/Applications/Xcode_13.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: sample_code/libsample_code_app.a(SampleRecordFormatDataLayout.cpp.o) has no symbols
/Applications/Xcode_13.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: sample_code/libsample_code_app.a(SampleImageReader.cpp.o) has no symbols
/Applications/Xcode_13.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: sample_code/libsample_code_app.a(SampleRecordAndPlay.cpp.o) has no symbols
/Applications/Xcode_13.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: sample_code/libsample_code_app.a(SampleRecordFormatDataLayout.cpp.o) has no symbols
warning: /Applications/Xcode_13.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: sample_code/libsample_code_app.a the table of contents is empty (no object file members in the library define global symbols)
[132/132] Linking CXX executable tools/vrs/test_vrscli
~/Cache/vrs_build$ 
```

To see the version of the tools & libraries:
```
$ brew install ninja cmake ccache googletest glog fmt cereal libpng jpeg lz4 zstd xxhash boost
Warning: Treating cmake as a formula. For the cask, use homebrew/cask/cmake
Warning: ninja 1.11.0 is already installed and up-to-date.
To reinstall 1.11.0, run:
  brew reinstall ninja
Warning: cmake 3.23.1_1 is already installed and up-to-date.
To reinstall 3.23.1_1, run:
  brew reinstall cmake
Warning: ccache 4.6.1_1 is already installed and up-to-date.
To reinstall 4.6.1_1, run:
  brew reinstall ccache
Warning: googletest 1.11.0 is already installed and up-to-date.
To reinstall 1.11.0, run:
  brew reinstall googletest
Warning: glog 0.6.0 is already installed and up-to-date.
To reinstall 0.6.0, run:
  brew reinstall glog
Warning: fmt 8.1.1_1 is already installed and up-to-date.
To reinstall 8.1.1_1, run:
  brew reinstall fmt
Warning: cereal 1.3.2 is already installed and up-to-date.
To reinstall 1.3.2, run:
  brew reinstall cereal
Warning: libpng 1.6.37 is already installed and up-to-date.
To reinstall 1.6.37, run:
  brew reinstall libpng
Warning: jpeg 9e is already installed and up-to-date.
To reinstall 9e, run:
  brew reinstall jpeg
Warning: lz4 1.9.3 is already installed and up-to-date.
To reinstall 1.9.3, run:
  brew reinstall lz4
Warning: zstd 1.5.2 is already installed and up-to-date.
To reinstall 1.5.2, run:
  brew reinstall zstd
Warning: xxhash 0.8.1 is already installed and up-to-date.
To reinstall 0.8.1, run:
  brew reinstall xxhash
Warning: boost 1.78.0_1 is already installed and up-to-date.
To reinstall 1.78.0_1, run:
  brew reinstall boost
```

Can you run `brew upgrade` and compare with what I have above, to be sure we both use the latest versions of the libraries coming from brew?

**Comment by lmathia2** [comment]
I tried the upgrade, and this is what I have
```brew list --versions -q  ninja cmake ccache googletest glog fmt cereal libpng jpeg lz4 zstd xxhash boost
boost 1.78.0_1
ccache 4.6.1_1
cereal 1.3.2
cmake 3.23.1_1
fmt 8.1.1_1
glog 0.6.0
googletest 1.11.0
jpeg 9e
libpng 1.6.37
lz4 1.9.3
ninja 1.11.0
xxhash 0.8.1
zstd 1.5.2```


Also, running the build, I get the same error
```
(base) mathiasl-mbp:src mathiasl$ cmake -S oss-vrs -B vrs_build  '-GCodeBlocks - Ninja'
CMake Error: The source directory "/Users/mathiasl/Projects/cvpr_release_data/src/oss-vrs" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
(base) mathiasl-mbp:src mathiasl$ ls vrs/
(base) mathiasl-mbp:src mathiasl$ cmake -S vrs -B vrs_build  '-GCodeBlocks - Ninja'
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_CXX_COMPILER: /Library/Developer/CommandLineTools/usr/bin/c++
-- CMAKE_CXX_COMPILER_VERSION: 13.1.6.13160021
-- CCACHE enabled
-- Found Boost: /Users/mathiasl/.brew/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: filesystem chrono date_time system thread
-- Found Lz4: /Users/mathiasl/.brew/lib/liblz4.dylib
-- Found Zstd: /Users/mathiasl/.brew/lib/libzstd.dylib
-- Found xxHash: /Users/mathiasl/.brew/lib/libxxhash.dylib
-- Found ZLIB: /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libz.tbd (found version "1.2.11")
-- Found PNG: /Users/mathiasl/.brew/lib/libpng.dylib (found version "1.6.37")
-- Found JPEG: /Users/mathiasl/.brew/lib/libjpeg.dylib (found version "90")
-- Found GTest: /Users/mathiasl/.brew/anaconda3/lib/cmake/GTest/GTestConfig.cmake (found version "1.10.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mathiasl/Projects/cvpr_release_data/src/vrs_build
(base) mathiasl-mbp:src mathiasl$ cd vrs_build/
(base) mathiasl-mbp:vrs_build mathiasl$ ninja
[105/132] Linking CXX executable vrs/os/test_vrs_os
FAILED: vrs/os/test_vrs_os vrs/os/test_vrs_os[1]_tests.cmake /Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/os/test_vrs_os[1]_tests.cmake
: && /Users/mathiasl/.brew/bin/ccache /Library/Developer/CommandLineTools/usr/bin/c++ -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  vrs/os/CMakeFiles/test_vrs_os.dir/test/TimeTest.cpp.o vrs/os/CMakeFiles/test_vrs_os.dir/test/EventUnitTest.cpp.o vrs/os/CMakeFiles/test_vrs_os.dir/test/UtilsTest.cpp.o -o vrs/os/test_vrs_os  -Wl,-rpath,/Users/mathiasl/.brew/lib  vrs/os/libvrs_os.a  vrs/oss/TestDataDir/libvrs_oss_testdatadir.a  vrs/os/libvrs_os.a  vrs/oss/logging/libvrs_logging.a  /Users/mathiasl/.brew/lib/libfmt.8.1.1.dylib  /Users/mathiasl/.brew/lib/libboost_system-mt.dylib  /Users/mathiasl/.brew/lib/libboost_filesystem-mt.dylib  /Users/mathiasl/.brew/lib/libboost_atomic-mt.dylib  /Users/mathiasl/.brew/lib/libboost_thread-mt.dylib  /Users/mathiasl/.brew/lib/libboost_chrono-mt.dylib  /Users/mathiasl/.brew/lib/libboost_date_time-mt.dylib  /Users/mathiasl/.brew/anaconda3/lib/libgtest_main.1.10.0.dylib  /Users/mathiasl/.brew/anaconda3/lib/libgtest.1.10.0.dylib && cd /Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/os && /Users/mathiasl/.brew/Cellar/cmake/3.23.1_1/bin/cmake -D TEST_TARGET=test_vrs_os -D TEST_EXECUTABLE=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/os/test_vrs_os -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/os -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_FILTER= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=test_vrs_os_TESTS -D CTEST_FILE=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/os/test_vrs_os[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=5 -D TEST_XML_OUTPUT_DIR= -P /Users/mathiasl/.brew/Cellar/cmake/3.23.1_1/share/cmake/Modules/GoogleTestAddTests.cmake
Undefined symbols for architecture x86_64:
  "typeinfo for testing::Test", referenced from:
      typeinfo for TimeTest in TimeTest.cpp.o
      typeinfo for EventTest in EventUnitTest.cpp.o
      typeinfo for FileTest in UtilsTest.cpp.o
      typeinfo for GetCurrentExecutablePathTest in UtilsTest.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[106/132] Linking CXX executable vrs/helpers/test_vrs_helpers
FAILED: vrs/helpers/test_vrs_helpers vrs/helpers/test_vrs_helpers[1]_tests.cmake /Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/helpers/test_vrs_helpers[1]_tests.cmake
: && /Users/mathiasl/.brew/bin/ccache /Library/Developer/CommandLineTools/usr/bin/c++ -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  vrs/helpers/CMakeFiles/test_vrs_helpers.dir/test/StringsTest.cpp.o -o vrs/helpers/test_vrs_helpers  -Wl,-rpath,/Users/mathiasl/.brew/lib  vrs/helpers/libvrs_helpers.a  vrs/os/libvrs_os.a  vrs/oss/logging/libvrs_logging.a  /Users/mathiasl/.brew/lib/libfmt.8.1.1.dylib  /Users/mathiasl/.brew/lib/libboost_system-mt.dylib  /Users/mathiasl/.brew/lib/libboost_filesystem-mt.dylib  /Users/mathiasl/.brew/lib/libboost_atomic-mt.dylib  /Users/mathiasl/.brew/lib/libboost_thread-mt.dylib  /Users/mathiasl/.brew/lib/libboost_chrono-mt.dylib  /Users/mathiasl/.brew/lib/libboost_date_time-mt.dylib  /Users/mathiasl/.brew/anaconda3/lib/libgtest_main.1.10.0.dylib  /Users/mathiasl/.brew/anaconda3/lib/libgtest.1.10.0.dylib && cd /Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/helpers && /Users/mathiasl/.brew/Cellar/cmake/3.23.1_1/bin/cmake -D TEST_TARGET=test_vrs_helpers -D TEST_EXECUTABLE=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/helpers/test_vrs_helpers -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/helpers -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_FILTER= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=test_vrs_helpers_TESTS -D CTEST_FILE=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/helpers/test_vrs_helpers[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=5 -D TEST_XML_OUTPUT_DIR= -P /Users/mathiasl/.brew/Cellar/cmake/3.23.1_1/share/cmake/Modules/GoogleTestAddTests.cmake
Undefined symbols for architecture x86_64:
  "typeinfo for testing::Test", referenced from:
      typeinfo for StringsHelpersTester in StringsTest.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[107/132] Linking CXX executable vrs/utils/converters/test_vrs_utils_converters
FAILED: vrs/utils/converters/test_vrs_utils_converters vrs/utils/converters/test_vrs_utils_converters[1]_tests.cmake /Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/utils/converters/test_vrs_utils_converters[1]_tests.cmake
: && /Users/mathiasl/.brew/bin/ccache /Library/Developer/CommandLineTools/usr/bin/c++ -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  vrs/utils/converters/CMakeFiles/test_vrs_utils_converters.dir/test/Raw10ToGrey10ConverterTest.cpp.o -o vrs/utils/converters/test_vrs_utils_converters  -Wl,-rpath,/Users/mathiasl/.brew/lib  vrs/utils/converters/libvrs_utils_converters.a  vrs/os/libvrs_os.a  vrs/oss/logging/libvrs_logging.a  /Users/mathiasl/.brew/lib/libfmt.8.1.1.dylib  /Users/mathiasl/.brew/lib/libboost_system-mt.dylib  /Users/mathiasl/.brew/lib/libboost_filesystem-mt.dylib  /Users/mathiasl/.brew/lib/libboost_atomic-mt.dylib  /Users/mathiasl/.brew/lib/libboost_thread-mt.dylib  /Users/mathiasl/.brew/lib/libboost_chrono-mt.dylib  /Users/mathiasl/.brew/lib/libboost_date_time-mt.dylib  /Users/mathiasl/.brew/anaconda3/lib/libgtest_main.1.10.0.dylib  /Users/mathiasl/.brew/anaconda3/lib/libgtest.1.10.0.dylib && cd /Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/utils/converters && /Users/mathiasl/.brew/Cellar/cmake/3.23.1_1/bin/cmake -D TEST_TARGET=test_vrs_utils_converters -D TEST_EXECUTABLE=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/utils/converters/test_vrs_utils_converters -D TEST_EXECUTOR= -D TEST_WORKING_DIR=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/utils/converters -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_FILTER= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=test_vrs_utils_converters_TESTS -D CTEST_FILE=/Users/mathiasl/Projects/cvpr_release_data/src/vrs_build/vrs/utils/converters/test_vrs_utils_converters[1]_tests.cmake -D TEST_DISCOVERY_TIMEOUT=5 -D TEST_XML_OUTPUT_DIR= -P /Users/mathiasl/.brew/Cellar/cmake/3.23.1_1/share/cmake/Modules/GoogleTestAddTests.cmake
Undefined symbols for architecture x86_64:
  "typeinfo for testing::Test", referenced from:
      typeinfo for Raw10ToGrey10Converter_ContiguousImages_Test in Raw10ToGrey10ConverterTest.cpp.o
      typeinfo for Raw10ToGrey10Converter_NonContiguousImages_Test in Raw10ToGrey10ConverterTest.cpp.o
      typeinfo for Raw10ToGrey10Converter_InvalidInput_Test in Raw10ToGrey10ConverterTest.cpp.o
      typeinfo for Raw10ToGrey10Converter_ContiguousImagesMultipleOf4_Test in Raw10ToGrey10ConverterTest.cpp.o
      typeinfo for Raw10ToGrey10Converter_NonContiguousImagesMultipleOf4_Test in Raw10ToGrey10ConverterTest.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[110/132] Building CXX object vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o
FAILED: vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o
/Users/mathiasl/.brew/bin/ccache /Library/Developer/CommandLineTools/usr/bin/c++ -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DOSS_BUILD_MODE -I/Users/mathiasl/Projects/cvpr_release_data/src/vrs -I/Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/oss -isystem /Users/mathiasl/.brew/anaconda3/include -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -std=c++17 -MD -MT vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o -MF vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o.d -o vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o -c /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/test/FilteredFileReaderTest.cpp
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/test/FilteredFileReaderTest.cpp:25:
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/FilteredFileReader.h:27:
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/RecordFileReader.h:33:
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/RecordReaders.h:21:
/Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/ErrorCode.h:22:10: fatal error: 'fmt/format.h' file not found
#include <fmt/format.h>
         ^~~~~~~~~~~~~~
1 error generated.
[111/132] Building CXX object vrs/utils/xxhash/CMakeFiles/test_vrs_utils_xxhash.dir/test/xxhashTest.cpp.o
FAILED: vrs/utils/xxhash/CMakeFiles/test_vrs_utils_xxhash.dir/test/xxhashTest.cpp.o
/Users/mathiasl/.brew/bin/ccache /Library/Developer/CommandLineTools/usr/bin/c++ -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -I/Users/mathiasl/Projects/cvpr_release_data/src/vrs -isystem /Users/mathiasl/.brew/anaconda3/include -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -std=c++17 -MD -MT vrs/utils/xxhash/CMakeFiles/test_vrs_utils_xxhash.dir/test/xxhashTest.cpp.o -MF vrs/utils/xxhash/CMakeFiles/test_vrs_utils_xxhash.dir/test/xxhashTest.cpp.o.d -o vrs/utils/xxhash/CMakeFiles/test_vrs_utils_xxhash.dir/test/xxhashTest.cpp.o -c /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/xxhash/test/xxhashTest.cpp
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/xxhash/test/xxhashTest.cpp:21:
/Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/xxhash/xxhash.h:21:10: error: 'xxhash.h' file not found with <angled> include; use "quotes" instead
#include <xxhash.h>
         ^~~~~~~~~~
         "xxhash.h"
/Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/xxhash/xxhash.h:48:3: error: unknown type name 'XXH64_state_t'
  XXH64_state_t* xxh_{nullptr};
  ^
2 errors generated.
[112/132] Building CXX object vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o
FAILED: vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o
/Users/mathiasl/.brew/bin/ccache /Library/Developer/CommandLineTools/usr/bin/c++ -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DOSS_BUILD_MODE -I/Users/mathiasl/Projects/cvpr_release_data/src/vrs -I/Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/oss -isystem /Users/mathiasl/.brew/anaconda3/include -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -std=c++17 -MD -MT vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o -MF vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o.d -o vrs/utils/CMakeFiles/test_vrs_utils.dir/test/PixelFrameTest.cpp.o -c /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/test/PixelFrameTest.cpp
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/utils/test/PixelFrameTest.cpp:24:
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/RecordFileReader.h:33:
In file included from /Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/RecordReaders.h:21:
/Users/mathiasl/Projects/cvpr_release_data/src/vrs/vrs/ErrorCode.h:22:10: fatal error: 'fmt/format.h' file not found
#include <fmt/format.h>
         ^~~~~~~~~~~~~~
1 error generated.
[116/132] Building CXX object sample_apps/CMakeFiles/sample_recording_app.dir/SampleRecordingApp.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by SeaOtocinclus** [comment]
Did you clean your cache (the build folder) before launching build again?

**Comment by georges-berenger** [comment]
In your build error, I see `-isystem /Users/mathiasl/.brew/anaconda3/include`. If I inject an error in my build in the same cpp files, I get:
```
FAILED: vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o
/usr/local/bin/ccache /Applications/Xcode_13.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DOSS_BUILD_MODE -I/Users/gberenger/Cache/oss-vrs -I/Users/gberenger/Cache/oss-vrs/vrs/oss -isystem /usr/local/include -O3 -DNDEBUG -isysroot /Applications/Xcode_13.2.1_fb.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -std=c++17 -MD -MT vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o -MF vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o.d -o vrs/utils/CMakeFiles/test_vrs_utils.dir/test/FilteredFileReaderTest.cpp.o -c /Users/gberenger/Cache/oss-vrs/vrs/utils/test/FilteredFileReaderTest.cpp
/Users/gberenger/Cache/oss-vrs/vrs/utils/test/FilteredFileReaderTest.cpp:27:2: error:
#error
```
My library includes are at `-isystem /usr/local/include` and in particular, I find `/usr/local/include/fmt/format.h`, which appears to be missing.

So your build errors look related to how your homebrew is setup, and fmt is probably not installed in your `/Users/mathiasl/.brew/anaconda3/include` folder. It looks to me you have a quirky homebrew installation.

**Comment by lmathia2** [comment]
Yes, looks like it is because my brew installation is not as root, and so it is not defaulting to linking the necessary libraries to /usr/local/{include,lib}...

Adding these lines in my .bashrc fixed it
export PATH="$(brew --prefix)/bin:$PATH
export LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix)/lib"
export CPATH="$(brew --prefix)/include:$CPATH"

Thanks for all the help

**Comment by SeaOtocinclus** [comment]
Great, let me close the issue. Happy that we found the source of the issue and that you are able to have a successful build!
